### PR TITLE
Revert k8s changes

### LINKED ISSUE #277: middleware/kubernetes: -ENOCOMPILE
```
# github.com/miekg/coredns/middleware/kubernetes
middleware/kubernetes/controller.go:58: dns.svcLister.Store undefined (type cache.StoreToServiceLister has no field or method Store)
middleware/kubernetes/controller.go:167: not enough arguments in call to dns.svcLister.List
middleware/kubernetes/controller.go:172: cannot use &svcList (type *[]*"k8s.io/kubernetes/pkg/api".Service) as type *"k8s.io/kubernetes/pkg/api".ServiceList in return argument
middleware/kubernetes/controller.go:196: dns.svcLister.Store undefined (type cache.StoreToServiceLister has no field or method Store)
middleware/kubernetes/kubernetes.go:219: not enough arguments in call to k.APIConn.svcLister.List
middleware/kubernetes/kubernetes.go:224: svcList.Items undefined (type []*"k8s.io/kubernetes/pkg/api".Service has no field or method Items)
```

That's one fast moving api....

Would be nice to use something last fast moving, a _shrudder_ vendor this whole tree.

### PR DESCRIPTION
**Pull request by aledbf**
Reverts changes introduced in #278 https://github.com/kubernetes/kubernetes/pull/33230

fixes #277

### CODE REVIEW

**Comment by miekg** [comment]
lgtm
